name: Run Monkkee Tests and Publish Allure Report

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests
        run: mvn clean test

      - name: List Allure results
        run: ls -la target/allure-results

      - name: Download Allure CLI
        run: |
          curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.34.1/allure-2.34.1.zip
          unzip allure.zip
          echo "$(pwd)/allure-2.34.1/bin" >> $GITHUB_PATH

      - name: Generate Allure Report
        if: success()
        run: |
          if [ -d target/allure-results ] && [ "$(ls -A target/allure-results)" ]; then
            allure generate target/allure-results --clean -o target/allure-report
          else
            echo "No Allure results found — skipping report generation."
            exit 1
          fi

      - name: Upload Allure Report as Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/allure-report
